"""add attack type to ios_content

Revision ID: 2c21455cfa56
Revises: ccabb7f24ef3
Create Date: 2017-11-13 15:28:47.990422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c21455cfa56'
down_revision = 'ccabb7f24ef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    op.add_column('ios_content', sa.Column('attack', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ios_content', 'attack')
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    # ### end Alembic commands ###
