"""add accounts table

Revision ID: 37934908254d
Revises: cffcf5be8984
Create Date: 2018-04-12 17:02:43.096846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37934908254d'
down_revision = 'cffcf5be8984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app', sa.String(length=256), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.Column('macAddress', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['macAddress'], ['devices.macAddress'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    op.drop_table('accounts')
    # ### end Alembic commands ###
