"""empty message

Revision ID: 8a14eeb57652
Revises: 26ea15e47636
Create Date: 2017-11-05 14:44:45.854152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a14eeb57652'
down_revision = '26ea15e47636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    # ### end Alembic commands ###
