"""removing ios_content model

Revision ID: 95a7b755dd94
Revises: 0bad76bc67c4
Create Date: 2017-11-19 15:23:44.631359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95a7b755dd94'
down_revision = '0bad76bc67c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ios_content')
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    op.create_table('ios_content',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('device_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('macAddress', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('twoFa', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('applications', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('bookmarks', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('browsing_history', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('call_history', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('contacts', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('events', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('media', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('locations', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('networks', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('gmail_token', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('ios_token', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('updated_on', mysql.DATETIME(), nullable=True),
    sa.Column('attack', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('osVersion', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
