"""add action type

Revision ID: b51d83a8eaa7
Revises: 0c458ff8b331
Create Date: 2017-11-05 15:43:27.808025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51d83a8eaa7'
down_revision = '0c458ff8b331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    op.add_column('history', sa.Column('action', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'action')
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    # ### end Alembic commands ###
