"""add ios_content table

Revision ID: ccabb7f24ef3
Revises: dfd3b7e2e75d
Create Date: 2017-11-13 15:24:44.633647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccabb7f24ef3'
down_revision = 'dfd3b7e2e75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ios_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=30), nullable=True),
    sa.Column('macAddress', sa.String(length=64), nullable=True),
    sa.Column('twoFa', sa.String(length=15), nullable=True),
    sa.Column('applications', sa.String(length=15), nullable=True),
    sa.Column('bookmarks', sa.String(length=15), nullable=True),
    sa.Column('browsing_history', sa.String(length=15), nullable=True),
    sa.Column('call_history', sa.String(length=15), nullable=True),
    sa.Column('contacts', sa.String(length=15), nullable=True),
    sa.Column('events', sa.String(length=15), nullable=True),
    sa.Column('media', sa.String(length=15), nullable=True),
    sa.Column('locations', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.String(length=15), nullable=True),
    sa.Column('networks', sa.String(length=15), nullable=True),
    sa.Column('gmail_token', sa.String(length=15), nullable=True),
    sa.Column('ios_token', sa.String(length=15), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    op.drop_table('ios_content')
    # ### end Alembic commands ###
