"""First db commit

Revision ID: dfd3b7e2e75d
Revises: 
Create Date: 2017-11-08 12:56:43.762391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd3b7e2e75d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    # ### end Alembic commands ###
