"""add history table

Revision ID: e154dcaec472
Revises: 8a14eeb57652
Create Date: 2017-11-05 15:02:06.889887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e154dcaec472'
down_revision = '8a14eeb57652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executed_on', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(30), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index(op.f('ix_devices_macAddress'), 'devices', ['macAddress'], unique=False)
    # op.drop_index('ix_devices_macAddress', table_name='devices')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('ix_devices_macAddress', 'devices', ['macAddress'], unique=False)
    # op.drop_index(op.f('ix_devices_macAddress'), table_name='devices')
    op.drop_table('history')
    # ### end Alembic commands ###
